---
title: "Project visualization"
author: "Kamel"
date: "12/03/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

Chargement de nos données 'Données_météo.csv` et le lire
Les données date de 18/03/2020 à 12h40

```{r cars}
library(readr)
library(rgrs)
data_weather <- read_csv("Données_météo.csv")
data_weather$country <- as.factor(data_weather$country)
data_weather$name <- as.factor(data_weather$name)
data_weather$continent <- as.factor(data_weather$continent)
```

## Including Plots

You can also embed plots, for example:

```{r}
library(ggplot2)
ggplot(data_weather, aes(x=country , y=temp)) + geom_boxplot(color="blue")
```


```{r}
library(ggplot2)
ggplot(data_weather, aes(x=temp_min , y=temp_max)) + geom_point(aes(color=country)) + geom_smooth() +
  ggtitle("Température") +
  xlab("Température minimal") +
  ylab("Température maximal")
```


```{r}
library(ggplot2)
ggplot(data_weather, aes(x=humidity , y=(temp-feels_like) )) + geom_point(aes(color=country)) +
  ggtitle("Humidité par rapport a (température - température ressenté)") +
  xlab("Humidité") +
  ylab("Température")
```


```{r}
library(ggplot2)
ggplot(data_weather, aes(x=humidity , y=visibility)) + geom_point(aes(color=country)) + geom_smooth() +
  ggtitle("Humidité par rapport visibilité") +
  xlab("Humidité") +
  ylab("Visibilité")
```


```{r}
library(dplyr)
library(ggplot2)

by_country <- group_by(data_weather, country)
country1<-summarise(by_country, visibility = mean(visibility))
 
ggplot(country1, aes(country, visibility)) + geom_col(fill="blue") +
  ggtitle("Visibilité par Continent") +
  xlab("Pays") +
  ylab("Visibilité (KM)")

```


```{r}
library(dplyr)
library(ggplot2)

by_country <- group_by(data_weather, country)
country1<-summarise(by_country, humidity = mean(humidity))
 
ggplot(country1, aes(country, humidity)) + geom_col(fill="blue") +
  ggtitle("Humidité par Continent") +
  xlab("Pays") +
  ylab("Humidité")

```


```{r}
library(ggplot2)
ggplot(data_weather, aes(x=speed , y=pressure)) + geom_point(aes(color=country)) + geom_smooth() +
  ggtitle("Vitesse du vent par rapport préssion ") +
  xlab("Vitesse du vent") +
  ylab("Préssion")
```


```{r}
library(ggplot2) 
ggplot(data_weather, aes(x = country, y= mean(temp))) + geom_col(fill="blue")+
  ggtitle("Température par Pays") +
  xlab("Pays") +
  ylab("Température")

```


```{r}
library(dplyr)
library(ggplot2)

by_continent <- group_by(data_weather, continent)
dt_continent<-summarise(by_continent, temp = mean(temp))
 
ggplot(dt_continent, aes(continent, temp)) + geom_col(fill="blue") +
  ggtitle("Température par Continent") +
  xlab("Continent") +
  ylab("Température")

```


```{r}
rp99$prop.proprio <- 0
rp99[rp99$proprio >= mean(rp99$proprio), ]$prop.proprio <- 1
rp99$prop.proprio <- factor(rp99$prop.proprio, 0:1, c("non", "oui"))
ggplot(rp99) +
  aes(x = dipl.aucun, y = tx.chom, size = pop.tot, colour = prop.proprio) +
  geom_point(alpha = .5) +
  xlab("% sans diplôme") +
  ylab("Taux de chômage") +
  labs(size = "Population totale", colour = "Proportion de propriétaires supérieure à la moyenne") +
  theme(
    legend.position = "bottom",
    legend.box = "vertical"
  )

```


```{r}
library(dplyr)
library(ggplot2)

by_country <- group_by(data_weather, country)
country1<-summarise(by_country, temp = mean(temp))
 
ggplot(country1, aes(country, temp)) + geom_col(fill="blue") +
  ggtitle("Température par Continent") +
  xlab("Pays") +
  ylab("Température") +
  scale_y_continuous(labels = scales::percent)

```


```{r}
library(dplyr)
library(ggplot2)

by_country <- group_by(data_weather, country)
country1<-summarise(by_country, temp = mean(temp))
 
ggplot(country1, aes(country, temp)) + geom_col(fill="blue") +
  ggtitle("Température par Continent") +
  xlab("Pays") +
  ylab("Température") 
#DT[order(as.numeric(rownames(DT)),decreasing = TRUE)]
```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
